### ISSUE TITLE
TODO: Status Bar elements

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#11]
- [x] Mouse coordinate tracker
  - [x] Redux-ified version
- [x] Selected features counter
- [x] "Powered by MapGuide" logo. If possibile, it should be combined with the existing ol.Attribution control already present
- [x] Scale Display (that is also tiled layer aware)
- [ ] Map size
