### ISSUE TITLE
TODO: Layout Templates

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#13]
We want to bring across the Fusion concept of layout templates that allows us to decouple application layout/presentation from application functionality, with the template html/css defining layout/presentation and the ApplicationDefinition fed to it defining the functionality.

This feature should be architected in a way that allows for compatibility with AJAX viewer Web Layout documents. Ideally it should also allow for supporting Fusion ApplicationDefinition documents as well.

 - [x] Implement a command registry allowing commands to be registered
    - [x] Have a redux-aware toolbar component that can initialize itself from registered commands in the command registry
 - [x] Implement a component registry
    - [x] Allow components to be registered by id
    - [x] All built-in components should already be registered by default
 - [x] Implement the notion of a "placeholder" component
    - [x] Requires component id and component props in order to be fully initialized
    - [x] When the layout initializes, it queries for the component from the registry by the specified id and renders it with the specified props
    - [ ] Use something like `react-redbox` to show a RSOD for placeholder components that failed to initialize.
 - [x] Implement the notion of a "layout" component. Layout components define the layout of the whole application which is a mix of intrinsic HTML elements and placeholder components.
     - [x] Implement a layout component registry
         - [x] Register a default layout component implementation that will automatically work with Web Layouts
         - [x] Allow component placeholder information to be queried from a layout
     - [x] When an application is initialized with a WebLayout resource id, use the default AJAX viewer layout component
 - [x] Expose component and layout component registries to the public API so that external components and layouts can be registered. This is the primary extension point for adding custom templates and components.
