### ISSUE TITLE
TODO: AJAX Viewer command parity

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#17]
To reach parity with the AJAX viewer, we need support for the following commands:
- [x] Pan up/down/left/right
- [x] Zoom In/Out
- [x] Zoom Selection
- [x] Previous view
- [x] Next view
- [x] Initial center and scale (could this just be an alias for initial view?)
- [x] Refresh Map
- [x] About
- [x] Select Within
- [x] Measure (overhaul, base it on: http://openlayers.org/en/latest/examples/measure.html)
- [x] View Options
- [x] Get Printable Page (aka. Quick Plot)
  - [x] Port over the geometry-based map capturer
- [x] Help
- [x] InvokeURL needs to support the "SpecifiedFrame" option
