### ISSUE TITLE
TODO: Integrate redux

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#19]
It has become clear that we've reached the point where we need a flux architecture in place to centralize and streamline the various component states. Our current top-level application component is a tangled mess of state and event handler spaghetti, which is a clear sign that we should have a flux implementation in place.

So let's integrate the best of the bunch: Redux.

 - [x] Add typings and npm packages
 - [x] Set up basic redux infrastructure (stores/reducers/actions)
 - [ ] Set up redux state branches for
     - [x] General configuration
     - [x] Runtime map state
     - [ ] Override selectable layers (from legend)
     - [x] Map view and navigation history stack
     - [x] Map selection
     - [x] Map loading progress
 - [x] Offload layer/group visibility to its own redux state branch. Have legend toggles push updates to it. Have the map respond to these branch changes and refresh the map on new state.
