### ISSUE TITLE
TODO: Refactor MapViewer to better integrate with redux

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#21]
The current MapViewer is a very stateful component that clashes with redux that wants to centralize all application state.

The MapViewer needs to be refactored so it can be as "dumb" as possible, where all viewer behavior is driven completely by its props

 - [x] SelectionPanel resets on each map pan/zoom, even if selection hasn't changed
 - [x] Need to figure out how to move current view state out of MapViewerBase it should be totally driven by the view props, ensuring the redux store is the central source of truth. Also we have to decide what is a more authoritative description of a map view. x/y/scale or extents?
 - [ ] Map Selection changes (via QueryMapFeatures) needs to move behind a redux action so that map selection updates properly follow uni-directional data flow principles.
