### ISSUE TITLE
NPM module sample checklist

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#229]
My attempt to dogfood the npm module by building a custom viewer out of it revealed the following issues:

 * [x] `stdicons` needs to be preset or menu/toolbar commands will have broken image links
    * [x] Probably demonstrating the use of `copy-webpack-plugin` would be sufficient
 * [x] Similarly we need some method to ensure that `viewer/server/TaskPane.html` is also copied across
 * [ ] ~~~For some reason I can actually get `@types/react-redux` typings to work. I guess it's safe to finally replace our `typings`-source version with the `@types` version~~~
 * [ ] ~~~The `tsconfig.npm.json` configuration should just output to `package` instead of `package/lib`, or see if there is some `package.json` trickery that allows us to import from `mapguide-react-layout/api/...` instead of `mapguide-react-layout/lib/api/...`~~~

**Comment by jumpinjackie** [comment]
The last 2 items I can't really do much about right now. Closing.
