### ISSUE TITLE
Missing Fusion widgets / features

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#243]
* [x] ~AddWMSLayer (NOTE: Technically this never was exposed in MapGuide as it did not have a corresponding widgetinfo, but the widget itself has utility)~ Superceded by #324 
 * [x] ~ActivityIndicator~ Not porting across. Redundant.
 * [x] ~ColorPicker~ Not porting across. I don't see the value of such a widget.
 * [x] ~LinkToView~ Not porting across. In favor of implementing #528 instead.
 * [x] ~SelectRadiusValue~ Not porting across. In favor of implementing #529 instead.
 * [x] ~PanQuery~ Not porting across. This is basically pan and selection modes combined. The value of porting this widget across is marginal.
 * [x] ~PanOnClick~ Not porting across. Never worked in Fusion (don't know when it broke)
 * [x] CenterSelection
