### ISSUE TITLE
TODO: InvokeURL command support

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#25]
- [x] Basic invocation support
- [x] Support disableIfSelectionEmpty
- [x] Support url targets
  - [x] Task Pane
  - [x] New Window (do this in an inline modal dialog?)
- [ ] Support additional parameters
