### ISSUE TITLE
TODO: Toolbar/Menu component

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#3]
Implement a re-usable toolbar/menu component that will serve the basis for the various toolbars and menus we'll need in this viewer.
- [ ] Allow labels/tooltips to be `string|Function`
- [x] ~~Should log warnings about nested flyouts. We currently only support one level of nesting (from the main toolbar). Flyouts within flyouts aren't possible yet.~~ We get nested menu support thanks to Blueprint (#91)
- [x] Add vertical orientation mode
  - [x] If possible, labels in vertical orientation should be rotated 90 degrees
  - [x] Flyout menus should slide out from the left or right side instead of bottom
- [x] Add support for separators
- [x] Nice to have: If items exceed the width of the toolbar, the toolbar should "fold" into a scrollable container
