### ISSUE TITLE
TODO: Modal dialog support

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#35]
- [x] Add redux branch for modals
- [x] Add actions to open/close modals. This pushes data to the redux branch
- [x] Add a modal launcher container component that listens on the redux branch for modal data and renders any open modals.
- [x] Allow size to specified on modals
- [x] Allow modals to be draggable
- [x] Support loading URLs into modals
