### ISSUE TITLE
TODO: Map Selection Property Palette

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#6]
We need a property palette to show attributes of selected features
- [x] Add support for scrolling through each selected feature
- [x] Add support for zooming to the current selected feature
- [x] Add support for highlighting the current selected feature. We can achieve this through a transient QUERYMAPFEATURES request (ie. set `PERSIST=0` and issue a selection XML only containing the current feature)
