### ISSUE TITLE
TODO: Task Pane

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#7]
The Task Pane provides a generic content container allowing for user-defined content/UIs to be shown alongside the map.

For the Task Pane to be of any use, we need to provide a client-side viewer API (#4) that should approximate what is provided by the AJAX viewer.
- [x] Redux-ification
  - [x] Add redux state branch for storing current url and task pane navigation stack
  - [x] Make home/forward back buttons into actions
  - [x] Redundant URL pushes are happening with submitted URLs. For example, run the buffer tool and submit. An NRE is happening (although the buffer succeeds)
- FIXME
  - [x] If loading a relative URL, both it and an absolute version are pushed to the navigation stack
- [x] Try to find a way to have the iframe not add actual browser history entries when navigating. Normally, one would destroy the current and re-create the iframe with the new URL (http://stackoverflow.com/questions/821359/reload-an-iframe-without-adding-to-the-history), but React's virtual DOM is most likely causing the iframe to be re-used
