### ISSUE TITLE
TODO: Legend

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#9]
- [x] Add support for expanding/collapsing layer groups
 - [x] Add support for toggling selectability of selectable layers
 - [x] Add support for retaining client-side expansion states between legend refreshes (from a new DESCRIBERUNTIMEMAP response)
